

- name: check running processes, killing ansible itslef, need to improve
# the following killing it ansible running process itself, 
# we may need to call the working shell script
# shell: "ps -ef | grep -v grep | grep -w {{ weblogic_domain }} | grep -v $0 | awk '{print $2}'"

  shell: "ps -ef |  grep  tail | grep uninstall | grep -v grep | awk '{print $2}' "
  register: running_processes

- name: kill running processes
  shell: "kill -9  {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"



#- wait_for:
#    path: "/proc/{{ item }}/status"
#    state: absent
#  with_items: "{{ running_processes.stdout_lines }}"
#  ignore_errors: yes
#  register: killed_processes

#- name: force kill stuck processes
#  shell: "kill -9 {{ item }}"
#  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"


