---
# tasks file for deploy


- hosts: localhost  
  remote_user: root
  gather_facts: no


# ---------------------------
# pre_taksks
# ---------------------------
  pre_tasks:

  # - set_fact:
  #   weblogic_domain: nsm202
  #  - include: roles/sanity_check/tasks/main.yml

  - include_role:
      name: sanity_check

  # ---------------------------
  # use roles
  # ---------------------------
  roles:

    - weblogic_stop
    - flashback_restore_point_create

    - deploy_md

      # dependencies:
      # Role dependencies are stored in the meta/main.yml of role directory, 
      # it contains a list of roles and parameters to insert before the specified role, 
      # - { role: aa }
      # - { role: bb }

    - weblogic_restart 

    - sanity_check
    # - test


  # -----------------------
  # use block
  # -----------------------
  tasks:
  - debug : msg="running block ..."

  - block:
    - include_role:
        name: deploy_md

    - include_role:
        name: sanity_check

    # --------------------------------
    # enable the following to test fail,
    # so that to run the rescue
    # - fail:
    #    msg: "deploy failed"
    # --------------------------------

    rescue:
      - include_role:
          name: rollback
     #     tasks_from: failure



# ----------------------------
# post_tasks is always run at the end.
# ----------------------------
  post_tasks:
    - include_role:
         name: sanity_check


# -----------------------
# how to use :
# -----------------------
# ap  -vvv  weblogic_stop.yml  -e  weblogic_domain=<nsm202>

     
